import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
<Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className>
        <div className>
          <div className>
            <p className>
              To-do Page
            </p>
            <Link className="subtitle" href='/login'>Click now to Start making a Todo List!</Link>
          </div>
        </div>
      </main>
    </>
  )
}

